### ISSUE TITLE
Стиль кода.

### ISSUE THREAD

**Issue by DmitryRyder** [IlyaHrushhyov/Catering#2]
1) Когда переносишь параметры конструктора на след. строку, то параметры должны быть на 1 табуляцию дальше верхней строки. 
2) Между методами в классах нужны отступы, в интерфейсах можно не делать.
3) Много пустых строк оставляешь.
4) Перед return всегда энтер - так читабельнее.
5) После того как пофиксишь поставь себе в приложение StyleCop.ruleset для проверки стиля кода.

**Comment by IlyaHrushhyov** [comment]
To see the latest changes on this issue, you have to check last commit named `Docker. Stylecop`.
